// Generated by scripts/registry/generate.mjs from feature-registry.json. Do not edit.
import { SERVICE_IDS } from "./rules.js";

export const FEATURE_REGISTRY = Object.freeze([
  Object.freeze({"id":"youtube.shorts","service":"youtube","name":"YouTube Shorts","tier":"free","freshDefault":true} as const),
  Object.freeze({"id":"youtube.related","service":"youtube","name":"Related videos","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"youtube.endscreen","service":"youtube","name":"End-of-video suggestions","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"youtube.autoplay","service":"youtube","name":"Autoplay prevention","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"youtube.comments","service":"youtube","name":"Comments","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"youtube.livechat","service":"youtube","name":"Live chat","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"instagram.reels","service":"instagram","name":"Instagram Reels","tier":"free","freshDefault":true} as const),
  Object.freeze({"id":"instagram.explore","service":"instagram","name":"Explore recommendations","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"instagram.stories","service":"instagram","name":"Stories and Highlights","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"instagram.suggested","service":"instagram","name":"Suggested accounts","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"instagram.threads","service":"instagram","name":"Threads links","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"facebook.reels","service":"facebook","name":"Facebook Reels","tier":"free","freshDefault":true} as const),
  Object.freeze({"id":"facebook.stories","service":"facebook","name":"Facebook Stories","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"facebook.videos","service":"facebook","name":"Videos and Watch","tier":"pro","freshDefault":false} as const),
  Object.freeze({"id":"facebook.sponsored","service":"facebook","name":"Desktop sidebar ads","tier":"pro","freshDefault":false} as const),
]);
export type FeatureId = (typeof FEATURE_REGISTRY)[number]["id"];
export const FEATURE_IDS: readonly FeatureId[] = Object.freeze(FEATURE_REGISTRY.map((f) => f.id));
export const TIKTOK_ALIAS = Object.freeze({"id":"tiktok.all","service":"tiktok","field":"services.tiktok","tier":"free","freshDefault":true} as const);
export type SettingsField = "globalOn" | `services.${(typeof SERVICE_IDS)[number]}` | `sites.${FeatureId}`;
export const SETTINGS_FIELDS: readonly SettingsField[] = Object.freeze([
  "globalOn", ...SERVICE_IDS.map((id) => `services.${id}` as const),
  ...FEATURE_IDS.map((id) => `sites.${id}` as const),
]);
