import { execFile, spawn } from "node:child_process";
import { copyFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { createInterface } from "node:readline";
import { promisify } from "node:util";
import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { FEATURE_REGISTRY, SERVICE_IDS, SETTINGS_FIELDS } from "@still/shared-types";
import { ChromeStorageAdapter } from "../chrome-adapter.js";
import { SettingsCache } from "../cache.js";
import { WKWebViewStorageAdapter } from "../wkwebview-adapter.js";
import { migrateSettingsV2 } from "../settings-v2.js";
import { parseStoredSettingsRecord } from "../settings-validation.js";
import upgrade from "../../../../shared-types/fixtures/upgrade-2.1.1.json";

// Upgrade from the shipped 2.1.1 records. The fixture holds the exact chrome.storage.local and App
// Group values the 2.1.1 browser extension and the 2.1.0 Apple app leave behind (generated by
// support/generate-upgrade-2.1.1-fixtures.mjs from ec1e68b/8a67977), plus what each person chose.
// Every current reader must hand those choices back exactly, never mistake a record it cannot place
// for a fresh install, and never write defaults over it. StillKit's Upgrade211FixtureTests reads
// the same file and the same expectations, which is what keeps the Swift reader in parity.

type Services = Record<(typeof SERVICE_IDS)[number], boolean>;
interface Expected {
  readonly globalOn: boolean;
  readonly services: Services;
  readonly updatedAt: number;
  readonly syncMetadata: { version: number; serverUpdatedAt: string; lastWriteId: string | null } | null;
  readonly syncEpoch: number | null;
  readonly retained?: {
    readonly root: Record<string, unknown>;
    readonly settings: Record<string, unknown>;
    readonly services: Record<string, unknown>;
  };
}
interface UpgradeCase {
  readonly name: string;
  readonly surface: "browser-storage" | "app-group";
  readonly present: boolean;
  readonly stored?: Record<string, unknown> | null;
  readonly rawJSON?: string | null;
  readonly expected: Expected | null;
}

const KEY = "still:settings";
const ORIGIN = "chrome-extension://still/";
const cases = upgrade.cases as unknown as UpgradeCase[];
const present = cases.filter((c): c is UpgradeCase & { expected: Expected } => c.present);
const absent = cases.filter((c) => !c.present);
const browserPresent = present.filter((c) => c.surface === "browser-storage");
const appGroup = cases.filter((c) => c.surface === "app-group");
// Current StillKit AtomicSettingsRecord.initialize accepts a zero clock only for "never-linked", so
// it holds these synced never-edited records under "unknown" while TypeScript migrates them.
// Recorded divergence; another change is aligning Swift with TypeScript. Keyed by case name on
// purpose: when that lands, these names move out of the set and the tests below must be updated.
const SWIFT_HOLDS_UNKNOWN = new Set(["browser-defaults-synced", "app-group-defaults-synced"]);

/** The stored record as the reader receives it: browser storage hands over an object, the native
 * bridge hands the Safari extension and WKWebView the App Group bytes as a JSON string. */
function storedObject(c: UpgradeCase): Record<string, unknown> {
  return c.surface === "app-group" ? JSON.parse(c.rawJSON!) : structuredClone(c.stored!);
}
const storedSettings = (c: UpgradeCase) => storedObject(c).settings as Record<string, unknown>;

/** A person's 2.1.1 service switch carries to that service's free feature; Pro extras, which 2.1.1
 * never offered, stay off. Nothing comes from the fresh-install defaults. */
function expectedSites(services: Services): Record<string, boolean> {
  return Object.fromEntries(FEATURE_REGISTRY.map((f) => [f.id, f.tier === "free" ? services[f.service] : false]));
}
function expectedUsableFields(e: Expected): Record<string, boolean> {
  return { globalOn: e.globalOn, ...Object.fromEntries(SERVICE_IDS.map((id) => [`services.${id}`, e.services[id]])) };
}
function readableLocal(c: UpgradeCase) {
  return { kind: "readable-local" as const, provenInitialization: c.expected!.updatedAt === 0 };
}

/** Synthetic chrome.storage.local holding exactly the fixture value (or no key at all). */
function browser(c: UpgradeCase) {
  let area: Record<string, unknown> = c.present ? { [KEY]: storedObject(c) } : {};
  const local = {
    get: vi.fn(async (keys: string | string[]) => {
      const wanted = typeof keys === "string" ? [keys] : keys;
      return Object.fromEntries(wanted.filter((k) => Object.hasOwn(area, k)).map((k) => [k, structuredClone(area[k])]));
    }),
    set: vi.fn(async (values: Record<string, unknown>) => {
      area = { ...area, ...structuredClone(values) };
    }),
  };
  vi.stubGlobal("chrome", {
    storage: { local, onChanged: { addListener: vi.fn(), removeListener: vi.fn() } },
    runtime: { getURL: () => ORIGIN, sendMessage: vi.fn() },
  });
  return { local, area: () => structuredClone(area), hasKey: () => Object.hasOwn(area, KEY) };
}

function expectLegacyChoices(settings: { globalOn: unknown; services: unknown; updatedAt: unknown }, e: Expected) {
  expect(settings.globalOn).toBe(e.globalOn);
  for (const id of SERVICE_IDS) expect((settings.services as Services)[id], id).toBe(e.services[id]);
  expect(settings.updatedAt).toBe(e.updatedAt);
}

afterEach(() => vi.unstubAllGlobals());

describe("2.1.1 upgrade fixtures", () => {
  it("cover every required shape on both stores", () => {
    const names = cases.map((c) => c.name);
    for (const surface of ["browser", "app-group"]) {
      for (const shape of ["defaults-never-touched", "defaults-synced", "all-off", "mixed", "signed-in-synced", "legacy-pauses", "unknown-extra-fields"]) {
        expect(names).toContain(`${surface}-${shape}`);
      }
    }
    expect(upgrade.sources.browser).toMatch(/^ec1e68b /);
    expect(upgrade.sources.apple).toMatch(/^8a67977 /);
    // The records are what 2.1.1 itself wrote: legacy shape, no schema, retired pauses present.
    for (const c of present) {
      const settings = storedSettings(c);
      expect(settings.schemaVersion, c.name).toBeUndefined();
      expect(Array.isArray(settings.pauses), c.name).toBe(true);
      expect(storedObject(c).atomic, c.name).toBeUndefined();
    }
    // 2.1.0 wrote App Group settings only through SettingsBridge set, with the 2.1.1 web record:
    // pauses already emptied, the epoch always stamped, and no syncMetadata key while signed out.
    for (const c of appGroup.filter((g) => (g as { origin?: string }).origin === "written-by-2.1.0" && g.present)) {
      expect(storedSettings(c).pauses, c.name).toEqual([]);
      expect(Object.hasOwn(storedObject(c), "syncEpoch"), c.name).toBe(true);
    }
    const common = appGroup.filter((c) => c.present && !Object.hasOwn(storedObject(c), "syncMetadata") && storedObject(c).syncEpoch === 0);
    expect(common.map((c) => c.name)).toEqual(["app-group-all-off", "app-group-mixed"]);
    expect((cases.find((c) => c.name === "app-group-legacy-pauses") as { origin?: string }).origin).toBe("carried-from-pre-release");
  });
});

describe.each(present.map((c) => [c.name, c] as const))("upgrading %s", (_name, c) => {
  const e = c.expected;

  it("reads back the saved choices, sync metadata and epoch exactly", () => {
    const inputs = c.surface === "app-group" ? [c.rawJSON!, storedObject(c)] : [storedObject(c)];
    for (const input of inputs) {
      const record = parseStoredSettingsRecord(input);
      expect(record).not.toBeNull();
      expectLegacyChoices(record!.settings, e);
      expect(record!.settings.pauses).toEqual([]);
      expect(record!.syncMetadata).toEqual(e.syncMetadata);
      expect(record!.syncEpoch).toBe(e.syncEpoch ?? undefined);
    }
  });

  it("migrates to schema 2 with every choice preserved and nothing taken from defaults", () => {
    const result = migrateSettingsV2(storedSettings(c), readableLocal(c));
    if (result.status !== "ready") throw new Error(`${c.name} needs recovery: ${result.reason}`);
    const s = result.settings;
    expect(s.schemaVersion).toBe(2);
    expect(result.migrated).toBe(true);
    expectLegacyChoices(s, e);
    expect(s.sites).toEqual(expectedSites(e.services));
    expect(Object.keys(s.clocks).sort()).toEqual([...SETTINGS_FIELDS].sort());
    for (const field of SETTINGS_FIELDS) expect(s.clocks[field], field).toEqual({ baseRevision: 0, localStep: 0 });
    expect(Object.hasOwn(s, "pauses")).toBe(false);
    for (const [key, value] of Object.entries(e.retained?.settings ?? {})) expect(s[key], key).toEqual(value);
    for (const [key, value] of Object.entries(e.retained?.services ?? {})) expect(s.services[key], key).toEqual(value);
  });

  it("never treats the record as a fresh install when provenance is missing or claims fresh", () => {
    const unknown = migrateSettingsV2(storedSettings(c), { kind: "unknown" });
    expect(unknown).toMatchObject({ status: "recovery", reason: "missing-provenance" });
    if (unknown.status === "recovery") expect(unknown.usableFields).toEqual(expectedUsableFields(e));
    expect(migrateSettingsV2(storedSettings(c), { kind: "proven-fresh" })).toMatchObject({
      status: "recovery",
      reason: "provenance-conflict",
    });
  });
});

describe.each(browserPresent.map((c) => [c.name, c] as const))("Chrome/Firefox startup over %s", (_name, c) => {
  const e = c.expected;

  it("configured legacy builds hydrate the saved choices without writing", async () => {
    const h = browser(c);
    const cache = new SettingsCache(new ChromeStorageAdapter());
    await cache.hydrate();
    expectLegacyChoices(cache.current(), e);
    expect(cache.currentSyncMetadata()).toEqual(e.syncMetadata);
    expect(h.local.set).not.toHaveBeenCalled();
    expect(h.area()[KEY]).toEqual(c.stored);
  });

  it("atomic local builds migrate in place, keeping choices, sync state and unknown members", async () => {
    const h = browser(c);
    const authority = new ChromeStorageAdapter({ authority: true });
    // Includes the synced never-edited record (updatedAt 0), which StillKit holds instead; see
    // SWIFT_HOLDS_UNKNOWN.
    await authority.initializeAtomic("unknown");
    const saved = h.area()[KEY] as Record<string, any>;
    expectLegacyChoices(saved.settings, e);
    expect(saved.settings.schemaVersion).toBe(2);
    expect(saved.settings.sites).toEqual(expectedSites(e.services));
    expect(saved.settings.pauses).toEqual([]);
    expect(saved.syncMetadata).toEqual(e.syncMetadata);
    expect(saved.syncEpoch).toBe(e.syncEpoch ?? undefined);
    // Upgrade evidence never claims a pristine install or an account it has not seen.
    expect(saved.atomic).toMatchObject({ ownership: "unknown", scope: { accountId: null }, anchor: null, pending: [], held: {}, paused: null });
    for (const [key, value] of Object.entries(e.retained?.root ?? {})) expect(saved[key], key).toEqual(value);
    for (const [key, value] of Object.entries(e.retained?.settings ?? {})) expect(saved.settings[key], key).toEqual(value);
    for (const [key, value] of Object.entries(e.retained?.services ?? {})) expect(saved.settings.services[key], key).toEqual(value);
    expect(h.local.set).toHaveBeenCalledTimes(1);

    // A later wake reads the migrated record and leaves it alone.
    await authority.initializeAtomic("unknown");
    expect(h.local.set).toHaveBeenCalledTimes(1);
    expect(h.area()[KEY]).toEqual(saved);
  });

  it("refuses the install-only fresh path and leaves the record untouched", async () => {
    const h = browser(c);
    await expect(new ChromeStorageAdapter({ authority: true }).initializeFreshAtomic()).rejects.toThrow(
      "fresh-provenance-conflict",
    );
    expect(h.local.set).not.toHaveBeenCalled();
    expect(h.area()[KEY]).toEqual(c.stored);
  });
});

describe.each(absent.map((c) => [c.name, c] as const))("upgrading %s", (_name, c) => {
  it("has nothing to migrate and is never given a fabricated record", async () => {
    expect(c.expected).toBeNull();
    expect(migrateSettingsV2(null, { kind: "readable-local" })).toMatchObject({ status: "recovery", reason: "missing-data" });
    expect(migrateSettingsV2(undefined, { kind: "unknown" })).toMatchObject({ status: "recovery", reason: "missing-provenance" });
    if (c.surface !== "browser-storage") return;
    const h = browser(c);
    await expect(new ChromeStorageAdapter({ authority: true }).initializeAtomic("unknown")).rejects.toThrow("missing-provenance");
    const cache = new SettingsCache(new ChromeStorageAdapter());
    await cache.hydrate();
    expect(h.local.set).not.toHaveBeenCalled();
    expect(h.hasKey()).toBe(false);
  });
});

/** A synthetic WKWebView message port answering `get` with the exact App Group bytes. */
function appleWindow(c: UpgradeCase) {
  const posted: unknown[] = [];
  const postMessage = vi.fn(async (message: unknown) => {
    posted.push(message);
    if ((message as { kind?: unknown }).kind === "get") return c.rawJSON ?? "";
    throw new Error(`unexpected native message ${JSON.stringify(message)}`);
  });
  return { posted, adapter: new WKWebViewStorageAdapter({ webkit: { messageHandlers: { still: { postMessage } } } }) };
}

describe.each(appGroup.map((c) => [c.name, c] as const))("Apple app startup (legacy bridge) over %s", (_name, c) => {
  it("hydrates the saved choices and posts nothing back", async () => {
    const h = appleWindow(c);
    const cache = new SettingsCache(h.adapter);
    await cache.hydrate();
    expect(h.posted).toEqual([{ kind: "get" }]);
    if (!c.present) {
      expect(cache.legacyReadState().status).toBe("absent");
      return;
    }
    const e = c.expected!;
    expectLegacyChoices(cache.current(), e);
    expect(cache.current().pauses).toEqual([]);
    expect(cache.currentSyncMetadata()).toEqual(e.syncMetadata);
    // An absent counter is "never repointed", which the live cache holds as 0; a stored 0 or 1 is
    // taken as written.
    expect(cache.currentRecord().syncEpoch).toBe(e.syncEpoch ?? 0);
    expect(cache.legacyReadState().status).toBe("ready");
  });
});

describe.skipIf(process.platform !== "darwin")("Apple atomic startup through the compiled StillKit host", () => {
  let temporary: string;
  let binary: string;
  beforeAll(async () => {
    temporary = await mkdtemp(join(tmpdir(), "still-upgrade-211-native-"));
    binary = join(temporary, "writer");
    const root = resolve(import.meta.dirname, "../../../../..");
    await copyFile(join(import.meta.dirname, "support/atomic-settings-main.swift"), join(temporary, "main.swift"));
    const sources = ["StillSettings", "SharedSettingsStore", "SettingsBridge", "SettingsV2", "SettingsFieldOrder",
      "PackagedFeatureRegistry", "AtomicSettingsBacking", "AtomicSettingsRecord"];
    await promisify(execFile)("swiftc", [
      ...sources.map((name) => join(root, "apps/apple/StillKit/Sources/StillKit", `${name}.swift`)),
      join(temporary, "main.swift"), "-module-cache-path", join(temporary, "modules"), "-o", binary,
    ]);
  }, 120_000);
  afterAll(async () => {
    if (temporary) await rm(temporary, { recursive: true, force: true });
  });

  /** Same line protocol as atomic-settings.test.ts: bridge JSON in, one reply line out. */
  function host(directory: string) {
    const child = spawn(binary, [directory], { stdio: ["pipe", "pipe", "pipe"] });
    const queue: { resolve: (value: string) => void; reject: (e: Error) => void }[] = [];
    const lines = createInterface({ input: child.stdout });
    lines.on("line", (value) => queue.shift()?.resolve(value));
    child.on("exit", () => queue.splice(0).forEach((p) => p.reject(new Error("native exited"))));
    const post = (message: unknown) =>
      new Promise<string>((resolveReply, reject) => {
        queue.push({ resolve: resolveReply, reject });
        child.stdin.write((typeof message === "string" ? message : JSON.stringify(message)) + "\n");
      });
    return {
      post,
      adapter: new WKWebViewStorageAdapter({ webkit: { messageHandlers: { still: { postMessage: post } } } }),
      async close() {
        lines.close();
        if (child.exitCode === null && child.signalCode === null) {
          child.kill("SIGKILL");
          await new Promise((r) => child.once("exit", r));
        }
      },
    };
  }

  it.each(appGroup.map((c) => [c.name, c] as const))("%s keeps every choice through hydrate and initialize", async (name, c) => {
    const native = host(join(temporary, name));
    try {
      if (c.present) expect(await native.post(`replace:${c.rawJSON}`)).toBe("replaced");
      const shipped = c.rawJSON ?? "";
      expect(await native.post({ kind: "get" })).toBe(shipped);

      // Legacy bridge startup reads the shipped bytes and writes nothing.
      const cache = new SettingsCache(native.adapter);
      await cache.hydrate();
      expect(await native.post({ kind: "get" })).toBe(shipped);

      if (!c.present) {
        // Absence is not a fresh install: initialize refuses and nothing is fabricated.
        await expect(native.adapter.initializeAtomic("unknown")).rejects.toThrow("native-atomic-unavailable");
        expect(await native.post({ kind: "get" })).toBe("");
        return;
      }
      const e = c.expected!;
      expectLegacyChoices(cache.current(), e);

      if (SWIFT_HOLDS_UNKNOWN.has(name)) {
        // Current behavior, asserted deliberately: Swift holds rather than migrates, and the
        // shipped bytes stay exactly as 2.1.0 left them.
        await expect(native.adapter.initializeAtomic("unknown")).rejects.toThrow("native-atomic-unavailable");
        expect(await native.post({ kind: "get" })).toBe(shipped);
        return;
      }
      const migrated = await native.adapter.initializeAtomic("unknown");
      const saved = JSON.parse(await native.post({ kind: "get" })) as Record<string, any>;
      for (const record of [migrated as unknown as Record<string, any>, saved]) {
        expectLegacyChoices(record.settings, e);
        expect(record.settings.schemaVersion).toBe(2);
        expect(record.settings.sites).toEqual(expectedSites(e.services));
        expect(record.atomic).toMatchObject({ ownership: "unknown", scope: { accountId: null }, anchor: null, pending: [], held: {}, paused: null });
      }
      expect(migrated.syncMetadata).toEqual(e.syncMetadata);
      expect(migrated.syncEpoch).toBe(e.syncEpoch ?? undefined);
      // Absent stays absent and a stored 0 stays 0 in the native bytes.
      expect(Object.hasOwn(saved, "syncEpoch")).toBe(e.syncEpoch !== null);
      if (e.syncEpoch !== null) expect(saved.syncEpoch).toBe(e.syncEpoch);
      for (const [key, value] of Object.entries(e.retained?.root ?? {})) expect(saved[key], key).toEqual(value);
      for (const [key, value] of Object.entries(e.retained?.settings ?? {})) expect(saved.settings[key], key).toEqual(value);
      for (const [key, value] of Object.entries(e.retained?.services ?? {})) expect(saved.settings.services[key], key).toEqual(value);

      // A later wake leaves the migrated record alone.
      const bytes = await native.post({ kind: "get" });
      await native.adapter.initializeAtomic("unknown");
      expect(await native.post({ kind: "get" })).toBe(bytes);
    } finally {
      await native.close();
    }
  });
});
