import { afterEach, describe, expect, it, vi } from "vitest";
import { FEATURE_REGISTRY, SERVICE_IDS, SETTINGS_FIELDS } from "@still/shared-types";
import { ChromeStorageAdapter } from "../chrome-adapter.js";
import { SettingsCache } from "../cache.js";
import { migrateSettingsV2 } from "../settings-v2.js";
import { parseStoredSettingsRecord } from "../settings-validation.js";
import upgrade from "../../../../shared-types/fixtures/upgrade-2.1.1.json";

// Upgrade from the shipped 2.1.1 records. The fixture holds the exact chrome.storage.local and App
// Group values the 2.1.1 browser extension and the 2.1.0 Apple app leave behind (generated by
// support/generate-upgrade-2.1.1-fixtures.mjs from ec1e68b/8a67977), plus what each person chose.
// Every current reader must hand those choices back exactly, never mistake a record it cannot place
// for a fresh install, and never write defaults over it. StillKit's Upgrade211FixtureTests reads
// the same file and the same expectations, which is what keeps the Swift reader in parity.

type Services = Record<(typeof SERVICE_IDS)[number], boolean>;
interface Expected {
  readonly globalOn: boolean;
  readonly services: Services;
  readonly updatedAt: number;
  readonly syncMetadata: { version: number; serverUpdatedAt: string; lastWriteId: string | null } | null;
  readonly syncEpoch: number | null;
  readonly retained?: {
    readonly root: Record<string, unknown>;
    readonly settings: Record<string, unknown>;
    readonly services: Record<string, unknown>;
  };
}
interface UpgradeCase {
  readonly name: string;
  readonly surface: "browser-storage" | "app-group";
  readonly present: boolean;
  readonly stored?: Record<string, unknown> | null;
  readonly rawJSON?: string | null;
  readonly expected: Expected | null;
}

const KEY = "still:settings";
const ORIGIN = "chrome-extension://still/";
const cases = upgrade.cases as unknown as UpgradeCase[];
const present = cases.filter((c): c is UpgradeCase & { expected: Expected } => c.present);
const absent = cases.filter((c) => !c.present);
const browserPresent = present.filter((c) => c.surface === "browser-storage");

/** The stored record as the reader receives it: browser storage hands over an object, the native
 * bridge hands the Safari extension and WKWebView the App Group bytes as a JSON string. */
function storedObject(c: UpgradeCase): Record<string, unknown> {
  return c.surface === "app-group" ? JSON.parse(c.rawJSON!) : structuredClone(c.stored!);
}
const storedSettings = (c: UpgradeCase) => storedObject(c).settings as Record<string, unknown>;

/** A person's 2.1.1 service switch carries to that service's free feature; Pro extras, which 2.1.1
 * never offered, stay off. Nothing comes from the fresh-install defaults. */
function expectedSites(services: Services): Record<string, boolean> {
  return Object.fromEntries(FEATURE_REGISTRY.map((f) => [f.id, f.tier === "free" ? services[f.service] : false]));
}
function expectedUsableFields(e: Expected): Record<string, boolean> {
  return { globalOn: e.globalOn, ...Object.fromEntries(SERVICE_IDS.map((id) => [`services.${id}`, e.services[id]])) };
}
function readableLocal(c: UpgradeCase) {
  return { kind: "readable-local" as const, provenInitialization: c.expected!.updatedAt === 0 };
}

/** Synthetic chrome.storage.local holding exactly the fixture value (or no key at all). */
function browser(c: UpgradeCase) {
  let area: Record<string, unknown> = c.present ? { [KEY]: storedObject(c) } : {};
  const local = {
    get: vi.fn(async (keys: string | string[]) => {
      const wanted = typeof keys === "string" ? [keys] : keys;
      return Object.fromEntries(wanted.filter((k) => Object.hasOwn(area, k)).map((k) => [k, structuredClone(area[k])]));
    }),
    set: vi.fn(async (values: Record<string, unknown>) => {
      area = { ...area, ...structuredClone(values) };
    }),
  };
  vi.stubGlobal("chrome", {
    storage: { local, onChanged: { addListener: vi.fn(), removeListener: vi.fn() } },
    runtime: { getURL: () => ORIGIN, sendMessage: vi.fn() },
  });
  return { local, area: () => structuredClone(area), hasKey: () => Object.hasOwn(area, KEY) };
}

function expectLegacyChoices(settings: { globalOn: unknown; services: unknown; updatedAt: unknown }, e: Expected) {
  expect(settings.globalOn).toBe(e.globalOn);
  for (const id of SERVICE_IDS) expect((settings.services as Services)[id], id).toBe(e.services[id]);
  expect(settings.updatedAt).toBe(e.updatedAt);
}

afterEach(() => vi.unstubAllGlobals());

describe("2.1.1 upgrade fixtures", () => {
  it("cover every required shape on both stores", () => {
    const names = cases.map((c) => c.name);
    for (const surface of ["browser", "app-group"]) {
      for (const shape of ["defaults-never-touched", "defaults-synced", "all-off", "mixed", "signed-in-synced", "legacy-pauses", "unknown-extra-fields"]) {
        expect(names).toContain(`${surface}-${shape}`);
      }
    }
    expect(upgrade.sources.browser).toMatch(/^ec1e68b /);
    expect(upgrade.sources.apple).toMatch(/^8a67977 /);
    // The records are what 2.1.1 itself wrote: legacy shape, no schema, retired pauses present.
    for (const c of present) {
      const settings = storedSettings(c);
      expect(settings.schemaVersion, c.name).toBeUndefined();
      expect(Array.isArray(settings.pauses), c.name).toBe(true);
      expect(storedObject(c).atomic, c.name).toBeUndefined();
    }
  });
});

describe.each(present.map((c) => [c.name, c] as const))("upgrading %s", (_name, c) => {
  const e = c.expected;

  it("reads back the saved choices, sync metadata and epoch exactly", () => {
    const inputs = c.surface === "app-group" ? [c.rawJSON!, storedObject(c)] : [storedObject(c)];
    for (const input of inputs) {
      const record = parseStoredSettingsRecord(input);
      expect(record).not.toBeNull();
      expectLegacyChoices(record!.settings, e);
      expect(record!.settings.pauses).toEqual([]);
      expect(record!.syncMetadata).toEqual(e.syncMetadata);
      expect(record!.syncEpoch).toBe(e.syncEpoch ?? undefined);
    }
  });

  it("migrates to schema 2 with every choice preserved and nothing taken from defaults", () => {
    const result = migrateSettingsV2(storedSettings(c), readableLocal(c));
    if (result.status !== "ready") throw new Error(`${c.name} needs recovery: ${result.reason}`);
    const s = result.settings;
    expect(s.schemaVersion).toBe(2);
    expect(result.migrated).toBe(true);
    expectLegacyChoices(s, e);
    expect(s.sites).toEqual(expectedSites(e.services));
    expect(Object.keys(s.clocks).sort()).toEqual([...SETTINGS_FIELDS].sort());
    for (const field of SETTINGS_FIELDS) expect(s.clocks[field], field).toEqual({ baseRevision: 0, localStep: 0 });
    expect(Object.hasOwn(s, "pauses")).toBe(false);
    for (const [key, value] of Object.entries(e.retained?.settings ?? {})) expect(s[key], key).toEqual(value);
    for (const [key, value] of Object.entries(e.retained?.services ?? {})) expect(s.services[key], key).toEqual(value);
  });

  it("never treats the record as a fresh install when provenance is missing or claims fresh", () => {
    const unknown = migrateSettingsV2(storedSettings(c), { kind: "unknown" });
    expect(unknown).toMatchObject({ status: "recovery", reason: "missing-provenance" });
    if (unknown.status === "recovery") expect(unknown.usableFields).toEqual(expectedUsableFields(e));
    expect(migrateSettingsV2(storedSettings(c), { kind: "proven-fresh" })).toMatchObject({
      status: "recovery",
      reason: "provenance-conflict",
    });
  });
});

describe.each(browserPresent.map((c) => [c.name, c] as const))("Chrome/Firefox startup over %s", (_name, c) => {
  const e = c.expected;

  it("configured legacy builds hydrate the saved choices without writing", async () => {
    const h = browser(c);
    const cache = new SettingsCache(new ChromeStorageAdapter());
    await cache.hydrate();
    expectLegacyChoices(cache.current(), e);
    expect(cache.currentSyncMetadata()).toEqual(e.syncMetadata);
    expect(h.local.set).not.toHaveBeenCalled();
    expect(h.area()[KEY]).toEqual(c.stored);
  });

  it("atomic local builds migrate in place, keeping choices, sync state and unknown members", async () => {
    const h = browser(c);
    const authority = new ChromeStorageAdapter({ authority: true });
    // Includes the synced never-edited record (updatedAt 0). StillKit's initialize holds that one
    // for "unknown" ownership instead; see Upgrade211FixtureTests for the recorded divergence.
    await authority.initializeAtomic("unknown");
    const saved = h.area()[KEY] as Record<string, any>;
    expectLegacyChoices(saved.settings, e);
    expect(saved.settings.schemaVersion).toBe(2);
    expect(saved.settings.sites).toEqual(expectedSites(e.services));
    expect(saved.settings.pauses).toEqual([]);
    expect(saved.syncMetadata).toEqual(e.syncMetadata);
    expect(saved.syncEpoch).toBe(e.syncEpoch ?? undefined);
    // Upgrade evidence never claims a pristine install or an account it has not seen.
    expect(saved.atomic).toMatchObject({ ownership: "unknown", scope: { accountId: null }, anchor: null, pending: [], held: {}, paused: null });
    for (const [key, value] of Object.entries(e.retained?.root ?? {})) expect(saved[key], key).toEqual(value);
    for (const [key, value] of Object.entries(e.retained?.settings ?? {})) expect(saved.settings[key], key).toEqual(value);
    for (const [key, value] of Object.entries(e.retained?.services ?? {})) expect(saved.settings.services[key], key).toEqual(value);
    expect(h.local.set).toHaveBeenCalledTimes(1);

    // A later wake reads the migrated record and leaves it alone.
    await authority.initializeAtomic("unknown");
    expect(h.local.set).toHaveBeenCalledTimes(1);
    expect(h.area()[KEY]).toEqual(saved);
  });

  it("refuses the install-only fresh path and leaves the record untouched", async () => {
    const h = browser(c);
    await expect(new ChromeStorageAdapter({ authority: true }).initializeFreshAtomic()).rejects.toThrow(
      "fresh-provenance-conflict",
    );
    expect(h.local.set).not.toHaveBeenCalled();
    expect(h.area()[KEY]).toEqual(c.stored);
  });
});

describe.each(absent.map((c) => [c.name, c] as const))("upgrading %s", (_name, c) => {
  it("has nothing to migrate and is never given a fabricated record", async () => {
    expect(c.expected).toBeNull();
    expect(migrateSettingsV2(null, { kind: "readable-local" })).toMatchObject({ status: "recovery", reason: "missing-data" });
    expect(migrateSettingsV2(undefined, { kind: "unknown" })).toMatchObject({ status: "recovery", reason: "missing-provenance" });
    if (c.surface !== "browser-storage") return;
    const h = browser(c);
    await expect(new ChromeStorageAdapter({ authority: true }).initializeAtomic("unknown")).rejects.toThrow("missing-provenance");
    const cache = new SettingsCache(new ChromeStorageAdapter());
    await cache.hydrate();
    expect(h.local.set).not.toHaveBeenCalled();
    expect(h.hasKey()).toBe(false);
  });
});
