// Generated by scripts/registry/generate.mjs from feature-registry.json. Do not edit.
import Foundation

public struct PackagedFeature: Equatable, Sendable {
  public let id: String
  public let service: String
  public let name: String
  public let tier: String
  public let freshDefault: Bool
}

public enum PackagedFeatureRegistry {
  public static let features: [PackagedFeature] = [
    PackagedFeature(id: "youtube.shorts", service: "youtube", name: "YouTube Shorts", tier: "free", freshDefault: true),
    PackagedFeature(id: "youtube.related", service: "youtube", name: "Related videos", tier: "pro", freshDefault: false),
    PackagedFeature(id: "youtube.endscreen", service: "youtube", name: "End-of-video suggestions", tier: "pro", freshDefault: false),
    PackagedFeature(id: "youtube.autoplay", service: "youtube", name: "Autoplay prevention", tier: "pro", freshDefault: false),
    PackagedFeature(id: "youtube.comments", service: "youtube", name: "Comments", tier: "pro", freshDefault: false),
    PackagedFeature(id: "youtube.livechat", service: "youtube", name: "Live chat", tier: "pro", freshDefault: false),
    PackagedFeature(id: "instagram.reels", service: "instagram", name: "Instagram Reels", tier: "free", freshDefault: true),
    PackagedFeature(id: "instagram.explore", service: "instagram", name: "Explore recommendations", tier: "pro", freshDefault: false),
    PackagedFeature(id: "instagram.stories", service: "instagram", name: "Stories and Highlights", tier: "pro", freshDefault: false),
    PackagedFeature(id: "instagram.suggested", service: "instagram", name: "Suggested accounts", tier: "pro", freshDefault: false),
    PackagedFeature(id: "instagram.threads", service: "instagram", name: "Threads links", tier: "pro", freshDefault: false),
    PackagedFeature(id: "facebook.reels", service: "facebook", name: "Facebook Reels", tier: "free", freshDefault: true),
    PackagedFeature(id: "facebook.stories", service: "facebook", name: "Facebook Stories", tier: "pro", freshDefault: false),
    PackagedFeature(id: "facebook.videos", service: "facebook", name: "Videos and Watch", tier: "pro", freshDefault: false),
    PackagedFeature(id: "facebook.sponsored", service: "facebook", name: "Desktop sidebar ads", tier: "pro", freshDefault: false),
  ]
  public static let serviceIDs = ["youtube", "instagram", "tiktok", "facebook"]
  public static let featureIDs = features.map { $0.id }
  public static let settingsFields = ["globalOn"] + serviceIDs.map { "services.\($0)" } + featureIDs.map { "sites.\($0)" }
  public static let tiktokAlias = "tiktok.all"
  public static let tiktokField = "services.tiktok"
}
