import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const root = fileURLToPath(new URL("../../", import.meta.url));
const registry = JSON.parse(
  readFileSync(
    resolve(root, "packages/shared-types/src/feature-registry.json"),
    "utf8",
  ),
);
const features = registry.features;
const ids = features.map((f) => f.id);
if (
  ids.length !== 15 ||
  new Set(ids).size !== 15 ||
  features.filter((f) => f.tier === "pro").length !== 12 ||
  features.some(
    (f) =>
      !["youtube", "instagram", "facebook"].includes(f.service) ||
      !f.id.startsWith(`${f.service}.`) ||
      !["free", "pro"].includes(f.tier) ||
      f.freshDefault !== (f.tier === "free"),
  ) ||
  JSON.stringify(registry.tiktokAlias) !==
    JSON.stringify({
      id: "tiktok.all",
      service: "tiktok",
      field: "services.tiktok",
      tier: "free",
      freshDefault: true,
    })
) {
  throw new Error("Invalid packaged registry");
}
const header =
  "// Generated by scripts/registry/generate.mjs from feature-registry.json. Do not edit.\n";
const ts =
  header +
  `import { SERVICE_IDS } from "./rules.js";\n\nexport const FEATURE_REGISTRY = Object.freeze([\n${features.map((f) => `  Object.freeze(${JSON.stringify(f)} as const),`).join("\n")}\n]);\nexport type FeatureId = (typeof FEATURE_REGISTRY)[number]["id"];\nexport const FEATURE_IDS: readonly FeatureId[] = Object.freeze(FEATURE_REGISTRY.map((f) => f.id));\nexport const TIKTOK_ALIAS = Object.freeze(${JSON.stringify(registry.tiktokAlias)} as const);\nexport type SettingsField = "globalOn" | \`services.\${(typeof SERVICE_IDS)[number]}\` | \`sites.\${FeatureId}\`;\nexport const SETTINGS_FIELDS: readonly SettingsField[] = Object.freeze([\n  "globalOn", ...SERVICE_IDS.map((id) => \`services.\${id}\` as const),\n  ...FEATURE_IDS.map((id) => \`sites.\${id}\` as const),\n]);\n`;
const swift =
  header +
  `import Foundation\n\npublic struct PackagedFeature: Equatable, Sendable {\n  public let id: String\n  public let service: String\n  public let name: String\n  public let tier: String\n  public let freshDefault: Bool\n}\n\npublic enum PackagedFeatureRegistry {\n  public static let features: [PackagedFeature] = [\n${features.map((f) => `    PackagedFeature(id: ${JSON.stringify(f.id)}, service: ${JSON.stringify(f.service)}, name: ${JSON.stringify(f.name)}, tier: ${JSON.stringify(f.tier)}, freshDefault: ${f.freshDefault}),`).join("\n")}\n  ]\n  public static let serviceIDs = ["youtube", "instagram", "tiktok", "facebook"]\n  public static let featureIDs = features.map { $0.id }\n  public static let settingsFields = ["globalOn"] + serviceIDs.map { "services.\\($0)" } + featureIDs.map { "sites.\\($0)" }\n  public static let tiktokAlias = "tiktok.all"\n  public static let tiktokField = "services.tiktok"\n}\n`;
for (const [path, content] of [
  ["packages/shared-types/src/feature-registry.ts", ts],
  ["apps/apple/StillKit/Sources/StillKit/PackagedFeatureRegistry.swift", swift],
]) {
  const target = resolve(root, path);
  if (process.argv.includes("--check")) {
    if (readFileSync(target, "utf8") !== content)
      throw new Error(`Generated registry drift: ${path}`);
  } else writeFileSync(target, content);
}
