-- Read-only 0021 pre/post invariant: preserve all legacy values and all six existing ledgers.
-- Whole-row fingerprints include provider_source and every existing Apple observation/link field.
-- Values are compared privately by the accepted deploy operation; never print them.
select pg_catalog.jsonb_build_object(
  'auth.users', (select pg_catalog.count(*) from auth.users),
  'auth.users.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from auth.users r),
  'private.analytics_erasure_jobs', (select pg_catalog.count(*) from private.analytics_erasure_jobs),
  'private.analytics_erasure_jobs.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.analytics_erasure_jobs r),
  'private.analytics_erasure_targets', (select pg_catalog.count(*) from private.analytics_erasure_targets),
  'private.analytics_erasure_targets.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.analytics_erasure_targets r),
  'private.analytics_subjects', (select pg_catalog.count(*) from private.analytics_subjects),
  'private.analytics_subjects.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.analytics_subjects r),
  'private.paid_cutoff', (select pg_catalog.count(*) from private.paid_cutoff),
  'private.paid_cutoff.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.paid_cutoff r),
  'private.product_policy_owners', (select pg_catalog.count(*) from private.product_policy_owners),
  'private.product_policy_owners.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.product_policy_owners r),
  'private.product_policy_operations', (select pg_catalog.count(*) from private.product_policy_operations),
  'private.product_policy_operations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.product_policy_operations r),
  'private.product_policy_revisions', (select pg_catalog.count(*) from private.product_policy_revisions),
  'private.product_policy_revisions.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.product_policy_revisions r),
  'private.settings_anchors', (select pg_catalog.count(*) from private.settings_anchors),
  'private.settings_anchors.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.settings_anchors r),
  'private.settings_writes', (select pg_catalog.count(*) from private.settings_writes),
  'private.settings_writes.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.settings_writes r),
  'public.canary_state', (select pg_catalog.count(*) from public.canary_state),
  'public.canary_state.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.canary_state r),
  'public.entitlements', (select pg_catalog.count(*) from public.entitlements),
  'public.entitlements.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.entitlements r),
  'public.profiles', (select pg_catalog.count(*) from public.profiles),
  'public.profiles.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.profiles r),
  'public.revenuecat_events', (select pg_catalog.count(*) from public.revenuecat_events),
  'public.revenuecat_events.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.revenuecat_events r),
  'public.rule_sets', (select pg_catalog.count(*) from public.rule_sets),
  'public.rule_sets.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.rule_sets r),
  'private.access_observations', (select pg_catalog.count(*) from private.access_observations),
  'private.access_observations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.access_observations r),
  'private.access_rights', (select pg_catalog.count(*) from private.access_rights),
  'private.access_rights.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.access_rights r),
  'private.access_revocations', (select pg_catalog.count(*) from private.access_revocations),
  'private.access_revocations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.access_revocations r),
  'private.access_transfer_operations', (select pg_catalog.count(*) from private.access_transfer_operations),
  'private.access_transfer_operations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.access_transfer_operations r),
  'private.apple_access_observations', (select pg_catalog.count(*) from private.apple_access_observations),
  'private.apple_access_observations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.apple_access_observations r),
  'private.apple_access_link_operations', (select pg_catalog.count(*) from private.apple_access_link_operations),
  'private.apple_access_link_operations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.apple_access_link_operations r)
)::text;
