-- Read-only 0022 pre/post invariant. 0022 changes no existing row except one bounded repair:
-- RevenueCat-sourced rights already detached by an earlier account deletion (holder null) are
-- deactivated. Their identity (key, product, source, holder) is still compared; only their
-- active/revision/verified_at state is excluded, and their count must not change. Every other
-- access right and every legacy, settings, analytics, QA checkout, membership and negative-right
-- row must be byte-identical. Values are compared privately by the accepted deploy operation;
-- never print them.
select pg_catalog.jsonb_build_object(
  'auth.users', (select pg_catalog.count(*) from auth.users),
  'auth.users.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from auth.users r),
  'private.analytics_erasure_jobs', (select pg_catalog.count(*) from private.analytics_erasure_jobs),
  'private.analytics_erasure_jobs.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.analytics_erasure_jobs r),
  'private.analytics_erasure_targets', (select pg_catalog.count(*) from private.analytics_erasure_targets),
  'private.analytics_erasure_targets.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.analytics_erasure_targets r),
  'private.analytics_subjects', (select pg_catalog.count(*) from private.analytics_subjects),
  'private.analytics_subjects.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.analytics_subjects r),
  'private.paid_cutoff', (select pg_catalog.count(*) from private.paid_cutoff),
  'private.paid_cutoff.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.paid_cutoff r),
  'private.product_policy_owners', (select pg_catalog.count(*) from private.product_policy_owners),
  'private.product_policy_owners.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.product_policy_owners r),
  'private.product_policy_operations', (select pg_catalog.count(*) from private.product_policy_operations),
  'private.product_policy_operations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.product_policy_operations r),
  'private.product_policy_revisions', (select pg_catalog.count(*) from private.product_policy_revisions),
  'private.product_policy_revisions.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.product_policy_revisions r),
  'private.settings_anchors', (select pg_catalog.count(*) from private.settings_anchors),
  'private.settings_anchors.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.settings_anchors r),
  'private.settings_writes', (select pg_catalog.count(*) from private.settings_writes),
  'private.settings_writes.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.settings_writes r),
  'public.canary_state', (select pg_catalog.count(*) from public.canary_state),
  'public.canary_state.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.canary_state r),
  'public.entitlements', (select pg_catalog.count(*) from public.entitlements),
  'public.entitlements.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.entitlements r),
  'public.profiles', (select pg_catalog.count(*) from public.profiles),
  'public.profiles.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.profiles r),
  'public.revenuecat_events', (select pg_catalog.count(*) from public.revenuecat_events),
  'public.revenuecat_events.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.revenuecat_events r),
  'public.rule_sets', (select pg_catalog.count(*) from public.rule_sets),
  'public.rule_sets.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from public.rule_sets r),
  'private.access_observations', (select pg_catalog.count(*) from private.access_observations),
  'private.access_observations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.access_observations r),
  'private.access_rights', (select pg_catalog.count(*) from private.access_rights),
  'private.access_rights.identity', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('right_id',r.right_id,'environment',r.environment,'provider_key',r.provider_key,'provider_product',r.provider_product,'provider_source',r.provider_source,'holder',r.holder) order by r.right_id)::text,'[]')) from private.access_rights r),
  'private.access_rights.unchanged_state', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by r.right_id)::text,'[]')) from private.access_rights r where not (r.holder is null and r.provider_source = 'revenuecat')),
  'private.access_rights.repaired', (select pg_catalog.count(*) from private.access_rights r where r.holder is null and r.provider_source = 'revenuecat'),
  'private.access_revocations', (select pg_catalog.count(*) from private.access_revocations),
  'private.access_revocations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.access_revocations r),
  'private.access_transfer_operations', (select pg_catalog.count(*) from private.access_transfer_operations),
  'private.access_transfer_operations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.access_transfer_operations r),
  'private.apple_access_observations', (select pg_catalog.count(*) from private.apple_access_observations),
  'private.apple_access_observations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.apple_access_observations r),
  'private.apple_access_link_operations', (select pg_catalog.count(*) from private.apple_access_link_operations),
  'private.apple_access_link_operations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.apple_access_link_operations r),
  'private.qa_sandbox_subjects', (select pg_catalog.count(*) from private.qa_sandbox_subjects),
  'private.qa_sandbox_subjects.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.qa_sandbox_subjects r),
  'private.qa_sandbox_negative_rights', (select pg_catalog.count(*) from private.qa_sandbox_negative_rights),
  'private.qa_sandbox_negative_rights.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.qa_sandbox_negative_rights r),
  'private.qa_sandbox_purchase_operations', (select pg_catalog.count(*) from private.qa_sandbox_purchase_operations),
  'private.qa_sandbox_purchase_operations.fingerprint', (select pg_catalog.md5(coalesce(pg_catalog.jsonb_agg(pg_catalog.to_jsonb(r) order by pg_catalog.to_jsonb(r)::text)::text,'[]')) from private.qa_sandbox_purchase_operations r)
)::text;
